require("ibl").setup()
require("nvim-autopairs").setup()
require("todo-comments").setup()
require("trouble").setup()

require("user.plugins.cmp")
require("user.plugins.colorizer")
require("user.plugins.conform")
require("user.plugins.fidget")
require("user.plugins.fzf_lua")
require("user.plugins.lsp")
require("user.plugins.lualine")
require("user.plugins.undotree")
