require("nvim-autopairs").setup()
require("fidget").setup()
require("todo-comments").setup()
require("trouble").setup()
require("ibl").setup()

require("user.plugins.colorizer")
require("user.plugins.conform")
require("user.plugins.fzf_lua")
require("user.plugins.lualine")
require("user.plugins.cmp")
require("user.plugins.lsp")
require("user.plugins.undotree")
